config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: "admins/passwords",
    registrations: "admins/registrations",
  }

  devise_for :customers, skip: :all
  devise_scope :customer do
    get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
    post 'customers', to: 'public/registrations#create', as: :customer_registration
    get "customers/sign_in", to: "public/sessions#new", as: :new_customer_session
    post "customers/sign_in", to: "public/sessions#create", as: :customer_session
    delete "customers/sign_out", to: "public/sessions#destroy", as: :destroy_customer_session
  end

  scope module: :public do
    resources :customers do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get "offers" => "offers#offers_index"
      get "offered" => "offers#offered_index"
      get "orders/listing" => "orders#listing"
      get "orders/in_progress" => "orders#in_progress"
      get "orders/completed" => "orders#completed"
      get "product/index" => "products#index", as: :product_index
    end

    get "product/index_1" => "products#index_1", as: :product_index_1
    get "product/index_2" => "products#index_2", as: :product_index_2
    get "product/index_3" => "products#index_3", as: :product_index_3
    get "product/index_4" => "products#index_4", as: :product_index_4
    get "product/index_5" => "products#index_5", as: :product_index_5
    get "product/index_6" => "products#index_6", as: :product_index_6
    get "product/index_7" => "products#index_7", as: :product_index_7
    get "product/index_8" => "products#index_8", as: :product_index_8

    get "customer/:id/show_profile" => "customers#show_profile", as: :customer_show_profile
    get "customer/:id/likes" => "customers#likes_index", as: :customer_likes_index
    get 'customers/:id/new_profile' => "customers#profile_new", as: :customer_new_profile
    patch 'customers/:id/create_profile' => 'customers#profile_create', as: :customer_create_profile
    get 'customer/complete' => 'customers#complete', as: :customer_complete

    resources :products, only: [:new, :create, :show, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      resources :offers
      resource :orders
    end
    get "product/complete" => "products#complete"
    get "product/offer/complete" => "offers#complete"
    delete "product/:product_id/product_images/:product_image_id" => "product_images#destroy", as: :product_image
    get "product/order/complete" => "orders#complete"
    get "search" => "products#search"
  end

  namespace :admins do
    get "customers/innsyoku" => "customers#index_innsyoku"
    get "customers/sonota" => "customers#index_sonota"
    resources :customers, only: [:index, :show, :edit, :destroy, :update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get "offers" => "offers#offers_index"
      get "offered" => "offers#offered_index"
      get "orders/listing" => "orders#listing"
      get "orders/in_progress" => "orders#in_progress"
      get "orders/completed" => "orders#completed"
    end
    resources :products, only: [:index, :show, :edit,] do
     resources :offers, only: [:show, :destroy]
     resource :orders
    end
    get "customer/:id/likes" => "customers#likes_index", as: :customer_likes_index
    get "search" => "products#search"
  end



  root to: "homes#top"
  get "/about" => "homes#about"
  post "homes/guest_sign_in" => "homes#guest_sign_in"

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy

  has_many :likes, dependent: :destroy
  has_many :liked_users, through: :likes, source: :product

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed

  has_many :post_comments, dependent: :destroy

  has_many :offers, dependent: :destroy

  has_many :orders, dependent: :destroy

  enum customer_attribute: { "生産者": 0, "飲食店": 1, "その他ユーザー": 2 }

  attachment :customer_image


  def already_liked?(product)
    likes.exists?(product_id: product.id)
  end

  def follow(customer_id)
    relationships.create(followed_id: customer_id)
  end

  def unfollow(customer_id)
    relationships.find_by(followed_id: customer_id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end
end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!


  def index
    customers = Customer.where(customer_attribute: "生産者").all.order(created_at: :desc)
    @customers_on = customers.where(is_deleted: false)
    @customers_off = customers.where(is_deleted: true)
  end

  def index_innsyoku
    customers = Customer.where(customer_attribute: "飲食店").all.order(created_at: :desc)
    @customers_on = customers.where(is_deleted: false)
    @customers_off = customers.where(is_deleted: true)
  end

  def index_sonota
    customers = Customer.where(customer_attribute: "その他ユーザー").all.order(created_at: :desc)
    @customers_on = customers.where(is_deleted: false)
    @customers_off = customers.where(is_deleted: true)
  end

  def show
    @customer = Customer.find_by(id: params[:id])
  end

  def edit
    @customer = Customer.find_by(id: params[:id])
  end

  def update
    @customer = Customer.find_by(id: params[:id])
    @customer.update(customer_params)
    if @customer.save
      flash[:notice] = "会員情報の更新が完了しました"
      redirect_to admins_products_path
    else
      @customer.attributes = customer_params
      flash[:failed] = "会員情報の更新が失敗しました。"
      render :edit
    end
  end

  def likes_index
    @customer = Customer.find_by(id: params[:id])
  end










  private

  def customer_params
    params.require(:customer).permit(
      :customer_first_name,
      :customer_last_name,
      :customer_first_name_kane,
      :customer_last_name_kane,
      :postcode,
      :adress,
      :phone_numer,
      :is_deleted,
      :shop_name,
      :shop_description,
      :customer_attribute,
      :customer_image
    )
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Public::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admins/customers/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 plate">

      <div class="form-header">
        <h5>会員情報編集</h5>
      </div>
      <%= form_with model: @customer, url: admins_customer_path(@customer.id), local: true do |f| %>
        <div class="field">
          <%= f.label :"ショップ名" %><br />
          <%= f.text_field :shop_name, autofocus: true, style: "border: none", placeholder: "ショップ名", value: "#{@customer.customer_last_name}さんのショップ", class: "w-100" %>
        </div>

        <div class="field">
          <%= f.label :"ショップ説明" %><br />
          <%= f.text_area :shop_description, style: "border: none", placeholder: "ショップの説明文を入力してください。", rows: "5", class: "w-100" %>
        </div>

        <div class="field">
          <%= f.label :"ショップ画像" %><br />
          <%= f.attachment_field :customer_image %>
        </div>

        <div class="field">
          <%= f.label :"ユーザー属性" %><span>＊必須＊</span><br>

          <%= f.select :customer_attribute, Customer.customer_attributes.keys.to_a , prompt: "--選択してください--" %>
        </div>

        <%= f.label :"お名前" %>
        <div class="field">
          <%= f.text_field :customer_last_name, style: "border: none", placeholder: "(姓)" %>
        </div>

        <div class="field">
          <%= f.text_field :customer_first_name, style: "border: none", placeholder: "(名)" %>
        </div>
        <%= f.label :"お名前(カナ)" %>
        <div class="field">
          <%= f.text_field :customer_last_name_kane, style: "border: none", placeholder: "(姓カナ)" %>
        </div>

        <div class="field">
          <%= f.text_field :customer_first_name_kane, style: "border: none", placeholder: "(名カナ)" %>
        </div>

        <div class="field">
          <%= f.label :"郵便番号"%><br>
          <%= f.text_field :postcode, placeholder: "例）1234567" %>
        </div>

        <div class="field">
          <%= f.label :"住所"%><br>
          <%= f.text_field :address, placeholder: "例）東京都〇〇区〇〇町〇〇-〇〇-〇", class:" w-50" %>
        </div>

        <div class="field">
          <%= f.label :"電話番号" %><br>
          <%= f.text_field :phone_number, placeholder: "例）〇〇〇-〇〇〇-〇〇〇〇", class:" w-50" %>
        </div>

        <div class="field">
          <%= f.label :"メールアドレス"%><br>
          <%= f.email_field :email, placeholder: "例）〇〇〇〇@gmail.com", class:" w-50" %>
        </div>

        <div class="field">
          <%= f.label :"退会させる"%><br>
          <%= f.select :is_deleted, [["利用中", false],["退会中", true]],  class:" w-50" %>
        </div>



        <div class="actions">
          <%= f.submit "編集内容を保存する", class:"btn btn-success w-100" %>
        </div>

        <div class="actions">
          <%= link_to "ユーザー情報を完全に削除する", admins_customer_path(@customer.id), method: :delete, class:"btn btn-danger w-50", "data-confirm" => "本当に削除しますか？" %>
        </div>









      <% end %>


    </div>
  </div>
</div>

app/views/admins/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 plate">



      <div class="row">
        <div class="col-12">
          <div class="followers-header">
          <p><%= @customers_on.count %><br>利用中ユーザー</p>
        </div>
        <% @customers_on.each do |customer| %>
          <%= link_to admins_customer_path(customer.id) do %>
            <div class="follow-customer-block">
              <div class="follow-customers">
                  <%= attachment_image_tag customer, :customer_image, size: "50x50", fallback: 'no_image.jpg',class: "customer-image" %><br>
                  <%= customer.shop_name %><br>
              </div>
            </div>

          <% end %>
        <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <div class="followers-header">
            <p><%= @customers_off.count %><br>一時退会したユーザー</p>
          </div>
          <% @customers_off.each do |customer| %>
            <%= link_to admins_customer_path(customer.id) do %>
              <div class="follow-customer-block">
                <div class="follow-customers">
                    <%= attachment_image_tag customer, :customer_image, size: "50x50", fallback: 'no_image.jpg',class: "customer-image" %><br>
                    <%= customer.shop_name %><br>
                </div>
              </div>

            <% end %>
          <% end %>
        </div>
      </div>









    </div>
  </div>
</div>

app/views/admins/customers/index_innsyoku.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 plate">

      <div class="user-index-header">
        <h3>飲食店ユーザー</h3>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="followers-header">
          <p><%= @customers_on.count %><br>利用中ユーザー</p>
        </div>
        <% @customers_on.each do |customer| %>
          <%= link_to admins_customer_path(customer.id) do %>
            <div class="follow-customer-block">
              <div class="follow-customers">
                  <%= attachment_image_tag customer, :customer_image, size: "50x50", fallback: 'no_image.jpg',class: "customer-image" %><br>
                  <%= customer.shop_name %><br>
              </div>
            </div>

          <% end %>
        <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <div class="followers-header">
            <p><%= @customers_off.count %><br>一時退会したユーザー</p>
          </div>
          <% @customers_off.each do |customer| %>
            <%= link_to admins_customer_path(customer.id) do %>
              <div class="follow-customer-block">
                <div class="follow-customers">
                    <%= attachment_image_tag customer, :customer_image, size: "50x50", fallback: 'no_image.jpg',class: "customer-image" %><br>
                    <%= customer.shop_name %><br>
                </div>
              </div>

            <% end %>
          <% end %>
        </div>
      </div>









    </div>
  </div>
</div>

app/views/admins/customers/index_sonota.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 plate">
      <div class="user-index-header">
        <h3>その他ユーザー</h3>
      </div>
      <div class="row">
        <div class="col-12">
          <div class="followers-header">
          <p><%= @customers_on.count %><br>利用中ユーザー</p>
        </div>
        <% @customers_on.each do |customer| %>
          <%= link_to admins_customer_path(customer.id) do %>
            <div class="follow-customer-block">
              <div class="follow-customers">
                  <%= attachment_image_tag customer, :customer_image, size: "50x50", fallback: 'no_image.jpg',class: "customer-image" %><br>
                  <%= customer.shop_name %><br>
              </div>
            </div>

          <% end %>
        <% end %>
        </div>
      </div>

      <div class="row">
        <div class="col-12">
          <div class="followers-header">
            <p><%= @customers_off.count %><br>一時退会したユーザー</p>
          </div>
          <% @customers_off.each do |customer| %>
            <%= link_to admins_customer_path(customer.id) do %>
              <div class="follow-customer-block">
                <div class="follow-customers">
                    <%= attachment_image_tag customer, :customer_image, size: "50x50", fallback: 'no_image.jpg',class: "customer-image" %><br>
                    <%= customer.shop_name %><br>
                </div>
              </div>

            <% end %>
          <% end %>
        </div>
      </div>









    </div>
  </div>
</div>

app/views/admins/customers/likes_index.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 plate">
      <div class="like-index-header">
        <p>いいねした商品</p>
      </div>

      <div class="like-indexes">
        <div class="mypage-products">

          <% if @customer.likes.empty? %>
            <h6>まだ商品はありません</h6>
          <% else %>
            <% @customer.likes.each do |like| %>
              <%= link_to product_path(like.product.id) do %>
                <div class="products_block">
                  <div class="products">
                    <div class="products_image">
                      <%= attachment_image_tag like.product.product_images.first, :image, format: 'jpeg', fallback: 'no_image.jpg', size: "100%", class: "rounded" %>
                    </div>
                    <% if like.product.is_sold == true %>
                      <div class="mypage-sold-wrap">
                        <p>sold out</p>
                      </div>
                    <% end %>
                    <p class="products_name"><%= like.product.name %></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>




    </div>
  </div>
</div>

app/views/admins/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-3 plate menu-lists">

      <div class="menu-list">
        <%= link_to "出品した商品 ", customer_product_index_path(@customer) %>
      </div>

      <div class="menu-list">
        <%= link_to "いいねした商品", admins_customer_likes_index_path(@customer.id) %>
      </div>
      <div class="menu-list">
        <%= link_to "ユーザー情報編集", edit_admins_customer_path(@customer.id) %>
      </div>

      <div class="menu-list">
        <%= link_to "#{ @customer.followings.count }フォロー中", admins_customer_followings_path(@customer.id) %>
      </div>
      <div class="menu-list">
        <%= link_to "#{ @customer.followers.count }フォロワー", admins_customer_followers_path(@customer.id) %>
      </div>
      <div class="menu-list">
        <%= link_to "#{ Offer.where(customer_id: @customer.id).count }オファーした商品", admins_customer_offers_path(@customer.id) %>
      </div>
      <div class="menu-list">
        <%= link_to "#{ Offer.where(offer_product_id: @customer.products.ids).count }オファーされた商品", admins_customer_offered_path(@customer.id) %>
      </div>
      <div class="menu-list">
        <%= link_to "オファー成立商品(準備中)", admins_customer_orders_listing_path(@customer.id) %>
      </div>
      <div class="menu-list">
        <%= link_to "オファー成立商品(取引中)", admins_customer_orders_in_progress_path(@customer.id) %>
      </div>
      <div class="menu-list">
        <%= link_to "オファー成立商品(取引完了済み)", admins_customer_orders_completed_path(@customer.id) %>
        </div>

    </div>

    <div class="col-sm-8 plate">
      <div class="mypage-profile">
        <%= attachment_image_tag @customer, :customer_image, size: "50x50", format: 'jpeg', fallback: 'no_image.jpg' ,class: "customer-image" %>
        <h5><%= @customer.shop_name %>さんのマイページ</h5>
        <p><%= @customer.shop_description %></p>
        <p>出品数:<%= @customer.products.count %>&nbsp;&nbsp;&nbsp;&nbsp;取引数:<%= @customer.orders.count %></p>
      </div>
      <div class="mypage-products">
        <% unless @customer.products.empty? %>
          <% @customer.products.each do |product| %>
            <%= link_to product_path(product) do %>
              <div class="products_block">
                <div class="products">
                  <div class="products_image">
                    <%= attachment_image_tag product.product_images.first, :image, format: 'jpeg', fallback: 'no_image.jpg', class: "product_image" %>
                  </div>
                  <% if product.is_sold == true %>
                    <div class="mypage-sold-wrap">
                      <p>sold out</p>
                    </div>
                  <% end %>
                  <p class="products_name"><%= product.name %></p>
                </div>
              </div>
            <% end %>
          <% end %>
        <% else %>
          <h7>まだ商品はありません</h7>
        <% end %>
      </div>

    </div>

  </div>
  <div class="product-registrate-btn">
    <%= link_to new_product_path do %>
      <p>出品</p>
      <i class="fas fa-camera"></i>
    <% end %>
  </div>
</div>