config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: "admins/passwords",
    registrations: "admins/registrations",
  }

  devise_for :customers, skip: :all
  devise_scope :customer do
    get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
    post 'customers', to: 'public/registrations#create', as: :customer_registration
    get "customers/sign_in", to: "public/sessions#new", as: :new_customer_session
    post "customers/sign_in", to: "public/sessions#create", as: :customer_session
    delete "customers/sign_out", to: "public/sessions#destroy", as: :destroy_customer_session
  end

  scope module: :public do
    resources :customers do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get "offers" => "offers#offers_index"
      get "offered" => "offers#offered_index"
      get "orders/listing" => "orders#listing"
      get "orders/in_progress" => "orders#in_progress"
      get "orders/completed" => "orders#completed"
      get "product/index" => "products#index", as: :product_index
    end

    get "product/index_1" => "products#index_1", as: :product_index_1
    get "product/index_2" => "products#index_2", as: :product_index_2
    get "product/index_3" => "products#index_3", as: :product_index_3
    get "product/index_4" => "products#index_4", as: :product_index_4
    get "product/index_5" => "products#index_5", as: :product_index_5
    get "product/index_6" => "products#index_6", as: :product_index_6
    get "product/index_7" => "products#index_7", as: :product_index_7
    get "product/index_8" => "products#index_8", as: :product_index_8

    get "customer/:id/show_profile" => "customers#show_profile", as: :customer_show_profile
    get "customer/:id/likes" => "customers#likes_index", as: :customer_likes_index
    get 'customers/:id/new_profile' => "customers#profile_new", as: :customer_new_profile
    patch 'customers/:id/create_profile' => 'customers#profile_create', as: :customer_create_profile
    get 'customer/complete' => 'customers#complete', as: :customer_complete

    resources :products, only: [:new, :create, :show, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      resources :offers
      resource :orders
    end
    get "product/complete" => "products#complete"
    get "product/offer/complete" => "offers#complete"
    delete "product/:product_id/product_images/:product_image_id" => "product_images#destroy", as: :product_image
    get "product/order/complete" => "orders#complete"
    get "search" => "products#search"
  end

  namespace :admins do
    get "customers/innsyoku" => "customers#index_innsyoku"
    get "customers/sonota" => "customers#index_sonota"
    resources :customers, only: [:index, :show, :edit, :destroy, :update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get "offers" => "offers#offers_index"
      get "offered" => "offers#offered_index"
      get "orders/listing" => "orders#listing"
      get "orders/in_progress" => "orders#in_progress"
      get "orders/completed" => "orders#completed"
    end
    resources :products, only: [:index, :show, :edit,] do
     resources :offers, only: [:show, :destroy]
     resource :orders
    end
    get "customer/:id/likes" => "customers#likes_index", as: :customer_likes_index
    get "search" => "products#search"
  end



  root to: "homes#top"
  get "/about" => "homes#about"
  post "homes/guest_sign_in" => "homes#guest_sign_in"

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :customer

  has_many :likes
  has_many :liked_users, through: :likes, source: :customer

  has_many :post_comments, dependent: :destroy

  has_many :product_images, dependent: :destroy
  accepts_attachments_for :product_images, attachment: :image

  belongs_to :genre

  # offer
  has_many :offers, class_name: "Offers", foreign_key: "offer_product_id"
  has_many :offer_products, through: :offers, source: :offer_product

  has_many :offereds, class_name: "Offers", foreign_key: "trade_product_id"
  has_many :trade_products, through: :offereds, source: :trade_product

  # order
  has_many :orders, class_name: "Orders", foreign_key: "order_product_id"
  has_many :order_products, through: :orders, source: :order_product

  has_many :ordereds, class_name: "Orders", foreign_key: "order_trade_product_id"
  has_many :order_trade_products, through: :ordereds, source: :order_trade_product

  validates :name, length: { maximum: 40 }
  validates :name, presence: true
  validates :description, length: { maximum: 1000 }
  validates :description, presence: true

  def self.search(keyword)
    where(["name like? OR description like?", "%#{keyword}%", "%#{keyword}%"])
  end

end

app/controllers/admins/products_controller.rb
class Admins::ProductsController < ApplicationController

  before_action :authenticate_admin!

  def index
    products = Product.all.order(created_at: :desc)

    @products_yasai = products.where(genre_id: 1)
    @products_kudamono = products.where(genre_id: 2)
    @products_kome_zakkoku = products.where(genre_id: 3)
    @products_kakousyokuhin = products.where(genre_id: 4)
    @products_inryou = products.where(genre_id: 5)
    @products_sonota = products.where(genre_id: 6)
  end

  def show
    @product = Product.find(params[:id])
    @post_comments = PostComment.where(product_id: @product.id)
    @post_comment = PostComment.new
  end

  def edit
    @product = Product.find(params[:id])
    @customer = @product.customer
  end

  def search
    products = Product.search(params[:keyword])
    unless params[:search] = "条件なし"
      @keyword = params[:keyword]
      return @products = products.where(is_sold: params[:is_sold], is_active: params[:is_active])
    else
      @products = products
      @keyword = params[:keyword]
    end

  end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    if customer_signed_in?
      @product = Product.new
    else
      redirect_to root_path
    end
  end

  def create
    @product = Product.new(product_params)
    @product.customer_id = current_customer.id
    @product.save
    redirect_to product_complete_path
  end

  def index
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

  def destroy
  end





  private

  def product_params
    params.require(:product).permit(:genre_id, :name, :description, :is_active, :image1_id, :image2_id, :image3_id)
  end
end

app/helpers/admins/products_helper.rb
module Admins::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admins/products/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-8 plate">

    <div class="edit-header">
      <p>管理編集画面</p>
    </div>

    <div class="row">
      <div class="col-12">
        <%= link_to customer_product_index_path(@customer.id) do %>
          <div class="mypage-profile">
            <%= attachment_image_tag @customer, :customer_image, size: "100x100", format: 'jpeg', fallback: 'no_image.jpg' ,class: "customer-image" %>
            <h5><%= @customer.shop_name %>さん</h5>
            <h6>id: <%= @customer.id %>&nbsp;&nbsp;&nbsp;&nbsp;商品id: <%= @product.id %></h6>

            <p>出品数:<%= @customer.products.count %>&nbsp;&nbsp;&nbsp;&nbsp;取引数:<%= @customer.orders.count %></p>

          </div>
        <% end %>
      </div>
    </div>

    <div class="edit-image-wrapper">
      <div class="edit-image-title">
        <h5>出品画像</h5>
        <p>最大3枚までアップロードできます</p>
      </div>


      <div class="edit-image-image-block">
        <div class="edit-image-image">
          <%= attachment_image_tag @product.product_images[0], :image, format: 'jpeg', fallback: 'no_image.jpg', size: '250x250', class: "edit-product_image rounded" %>
        </div>
        <% unless @product.product_images[0].nil? %>
          <%= link_to "削除", product_image_path(@product.id, @product.product_images[0].id), method: :delete %>
        <% end %>
      </div>

      <div class="edit-image-image-block">
        <div class="edit-image-image">
          <%= attachment_image_tag @product.product_images[1], :image, format: 'jpeg', fallback: 'no_image.jpg', size: '250x250', class: "edit-product_image rounded" %>
        </div>
        <% unless @product.product_images[1].nil? %>
          <%= link_to "削除", product_image_path(@product.id, @product.product_images[1].id), method: :delete %>
        <% end %>
      </div>

      <div class="edit-image-image-block">
        <div class="edit-image-image">
          <%= attachment_image_tag @product.product_images[2], :image, format: 'jpeg', fallback: 'no_image.jpg', size: '250x250', class: "edit-product_image rounded" %>
        </div>
        <% unless @product.product_images[2].nil? %>
          <%= link_to "削除", product_image_path(@product.id, @product.product_images[2].id), method: :delete %>
        <% end %>
      </div>


    </div>

    <%= form_with model: @product, local: true do |f| %>
      <%= f.attachment_field :product_images_images, multiple: true %>
      <p>アップしたい画像を全て添付してください。前に保存されていた画像は破棄されます。<br>
      Ctrlを押しながらクリックで複数追加できます。</p>
      <h4>商品名</h4>
      <%= f.text_field :name, class: "w-100" %>
      <h4>説明</h4>
      <%= f.text_area :description, rows: "5", class:"w-100" %>
      <div class="actions">
        <%= f.submit '商品の編集', class:"btn btn-danger w-100" %>
      </div>
    <% end %>

    <% if @product.is_active == true %>
      <%= form_with model: @product, local: true do |f| %>
        <div class="actions">
          <%= f.hidden_field :is_active, value: false %>
          <%= f.submit '出品を停止する', class:"btn btn-secondary w-100" %>
        </div>
      <% end %>
    <% else %>
      <%= form_with model: @product, local: true do |f| %>
        <div class="actions">
          <%= f.hidden_field :is_active, value: true %>
          <%= f.submit '出品を再開する', class:"btn btn-success w-100" %>
        </div>
      <% end %>
    <% end %>


    <div class="actions">
      <p>or</p>
    </div>
    <div class="actions">
      <%= link_to "商品を削除する", product_path(@product), method: :delete, "data-confirm" => "本当に削除しますか？", class:"btn btn-secondary w-100" %>
    </div>





    </div>
  </div>
</div>

app/views/admins/products/index.html.erb
<div class="container">
  <div class="row">
    <div  class="col-10 plate">



      <div class="search-form">
        <%= form_with url: admins_search_path, method: :get, local: true do |f| %>
          <%= f.text_field :keyword, placeholder: "キーワードを入力" %>
          <%= f.select :is_active, [["出品中", true],["出品停止中", false]] %>
          <%= f.select :is_sold, [["販売中", false],["売却済み", true]] %><br>
          <%= f.label :"条件がなければ→" %>
          <%= f.radio_button :search, value: "条件なし"  %>

          <%= f.submit '検索' %>
        <% end %>
      </div>
      <div class="top-menu-wrapper">

        <h5>商品一覧</h5>
        <h6>カテゴリー</h6>
        <a href="#yasai" class="btn btn-secondary">野菜</a>
        <a href="#kudamono" class="btn btn-secondary">果物</a>
        <a href="#kome_zakkoku" class="btn btn-secondary">米・雑穀</a>
        <a href="#kakousyokuhin" class="btn btn-secondary">加工食品</a>
        <a href="#inryou" class="btn btn-secondary">飲料</a>
        <a href="#sonota" class="btn btn-secondary">その他</a>
      </div>


      <div class="container">
        <div class="row">
          <div class="col-10 top-genre-wrapper" id="yasai">

            <div class="top-genre-header">
              <p>野菜</p>
            </div>
            <div class="top-genre-product-wrapper">
              <% @products_yasai.each do |product| %>
                <%= link_to product_path(product.id) do %>
                  <div class="products_block">
                    <div class="products">
                      <div class="products_image">
                        <%= attachment_image_tag product.product_images.first, :image, fallback: 'no_image.jpg', class: "product_image" %>
                      </div>
                      <% if product.is_sold == true %>
                      <div class="mypage-sold-wrap">
                        <p>sold out</p>
                      </div>
                      <% end %>
                      <% if product.is_active == false %>
                      <div class="mypage-is-active-wrap">
                        <p>出品停止中</p>
                      </div>
                      <% end %>
                      <p class="products_name"><%= product.name %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-10 top-genre-wrapper" id="kudamono">

            <div class="top-genre-header">
              <p>果物</p>
            </div>
            <div class="top-genre-product-wrapper">
              <% @products_kudamono.each do |product| %>
                <%= link_to product_path(product.id) do %>
                  <div class="products_block">
                    <div class="products">
                      <div class="products_image">
                        <%= attachment_image_tag product.product_images.first, :image, fallback: 'no_image.jpg', class: "product_image" %>
                      </div>
                      <p class="products_name"><%= product.name %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-10 top-genre-wrapper" id="kome_zakkoku">

            <div class="top-genre-header">
              <p>米・雑穀</p>
            </div>
            <div class="top-genre-product-wrapper">
              <% @products_kome_zakkoku.each do |product| %>
                <%= link_to product_path(product.id) do %>
                  <div class="products_block">
                    <div class="products">
                      <div class="products_image">
                        <%= attachment_image_tag product.product_images.first, :image, fallback: 'no_image.jpg', class: "product_image" %>
                      </div>
                      <p class="products_name"><%= product.name %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-10 top-genre-wrapper" id="kakousyokuhin">

            <div class="top-genre-header">
              <p>加工食品</p>
            </div>
            <div class="top-genre-product-wrapper">
              <% @products_kakousyokuhin.each do |product| %>
                <%= link_to product_path(product.id) do %>
                  <div class="products_block">
                    <div class="products">
                      <div class="products_image">
                        <%= attachment_image_tag product.product_images.first, :image, fallback: 'no_image.jpg', class: "product_image" %>
                      </div>
                      <p class="products_name"><%= product.name %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-10 top-genre-wrapper" id="inryou">

            <div class="top-genre-header">
              <p>飲料</p>
            </div>
            <div class="top-genre-product-wrapper">
              <% @products_inryou.each do |product| %>
                <%= link_to product_path(product.id) do %>
                  <div class="products_block">
                    <div class="products">
                      <div class="products_image">
                        <%= attachment_image_tag product.product_images.first, :image, fallback: 'no_image.jpg', class: "product_image" %>
                      </div>
                      <p class="products_name"><%= product.name %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-10 top-genre-wrapper" id="sonota">

            <div class="top-genre-header">
              <p>その他</p>
            </div>
            <div class="top-genre-product-wrapper">
              <% @products_sonota.each do |product| %>
                <%= link_to product_path(product.id) do %>
                  <div class="products_block">
                    <div class="products">
                      <div class="products_image">
                        <%= attachment_image_tag product.product_images.first, :image, fallback: 'no_image.jpg', class: "product_image" %>
                      </div>
                      <p class="products_name"><%= product.name %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>




    </div>
  </div>
</div>

app/views/admins/products/search.html.erb
<div class="container">
  <div class="row">
    <div class="col-10 category-index-wrapper">

      <div class="top-genre-header">
        <p>"<%= @keyword %>"で検索</p>
      </div>
      <div class="top-genre-product-wrapper">
        <% @products.each do |product| %>
          <%= link_to product_path(product.id) do %>
            <div class="products_block">
              <div class="products">
                <div class="products_image">
                  <%= attachment_image_tag product.product_images.first, :image, fallback: 'no_image.jpg', class: "product_image" %>
                </div>
                <% if product.is_sold == true %>
                <div class="mypage-sold-wrap">
                  <p>sold out</p>
                </div>
                <% end %>
                <% if product.is_active == false %>
                <div class="mypage-is-active-wrap">
                  <p>出品停止中</p>
                </div>
                <% end %>
                <p class="products_name"><%= product.name %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>