config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    passwords: "admins/passwords",
    registrations: "admins/registrations",
  }

  devise_for :customers, skip: :all
  devise_scope :customer do
    get 'customers/sign_up', to: 'public/registrations#new', as: :new_customer_registration
    post 'customers', to: 'public/registrations#create', as: :customer_registration
    get "customers/sign_in", to: "public/sessions#new", as: :new_customer_session
    post "customers/sign_in", to: "public/sessions#create", as: :customer_session
    delete "customers/sign_out", to: "public/sessions#destroy", as: :destroy_customer_session
  end

  scope module: :public do
    resources :customers do
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get "offers" => "offers#offers_index"
      get "offered" => "offers#offered_index"
      get "orders/listing" => "orders#listing"
      get "orders/in_progress" => "orders#in_progress"
      get "orders/completed" => "orders#completed"
      get "product/index" => "products#index", as: :product_index
    end

    get "product/index_1" => "products#index_1", as: :product_index_1
    get "product/index_2" => "products#index_2", as: :product_index_2
    get "product/index_3" => "products#index_3", as: :product_index_3
    get "product/index_4" => "products#index_4", as: :product_index_4
    get "product/index_5" => "products#index_5", as: :product_index_5
    get "product/index_6" => "products#index_6", as: :product_index_6
    get "product/index_7" => "products#index_7", as: :product_index_7
    get "product/index_8" => "products#index_8", as: :product_index_8

    get "customer/:id/show_profile" => "customers#show_profile", as: :customer_show_profile
    get "customer/:id/likes" => "customers#likes_index", as: :customer_likes_index
    get 'customers/:id/new_profile' => "customers#profile_new", as: :customer_new_profile
    patch 'customers/:id/create_profile' => 'customers#profile_create', as: :customer_create_profile
    get 'customer/complete' => 'customers#complete', as: :customer_complete

    resources :products, only: [:new, :create, :show, :edit, :update, :destroy] do
      resource :likes, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      resources :offers
      resource :orders
    end
    get "product/complete" => "products#complete"
    get "product/offer/complete" => "offers#complete"
    delete "product/:product_id/product_images/:product_image_id" => "product_images#destroy", as: :product_image
    get "product/order/complete" => "orders#complete"
    get "search" => "products#search"
  end

  namespace :admins do
    get "customers/innsyoku" => "customers#index_innsyoku"
    get "customers/sonota" => "customers#index_sonota"
    resources :customers, only: [:index, :show, :edit, :destroy, :update] do
      get 'followings' => 'relationships#followings', as: 'followings'
      get 'followers' => 'relationships#followers', as: 'followers'
      get "offers" => "offers#offers_index"
      get "offered" => "offers#offered_index"
      get "orders/listing" => "orders#listing"
      get "orders/in_progress" => "orders#in_progress"
      get "orders/completed" => "orders#completed"
    end
    resources :products, only: [:index, :show, :edit,] do
     resources :offers, only: [:show, :destroy]
     resource :orders
    end
    get "customer/:id/likes" => "customers#likes_index", as: :customer_likes_index
    get "search" => "products#search"
  end



  root to: "homes#top"
  get "/about" => "homes#about"
  post "homes/guest_sign_in" => "homes#guest_sign_in"

end

app/views/layouts/_admin_menu_modal.html.erb
<div class="admin-bar-menu admin-bar-menu-modal-wrapper">



  <div class="menu-btn-modal">
    <div class="admin-modal-btn"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"text-dark" %></div>
    <div class="admin-modal-btn"><%= link_to "商品一覧", admins_products_path, class:"text-dark" %></div>
    <div class="admin-modal-btn"><%= link_to "生産者一覧", admins_customers_path, class:"text-dark" %></div>
    <div class="admin-modal-btn"><%= link_to "飲食店一覧", admins_customers_innsyoku_path, class:"text-dark" %></div>
    <div class="admin-modal-btn"><%= link_to "その他ユーザー一覧", admins_customers_sonota_path, class:"text-dark" %></div>


  </div>
</div>

app/views/layouts/_bar_menu_modal.html.erb
<% if customer_signed_in? %>
  <div class="bar-menu bar-menu-modal-wrapper">
    <div class="profile-detail-modal">
      <%= attachment_image_tag current_customer, :customer_image, format: 'jpeg', fallback: 'no_image.jpg' ,class: "menu-modal-customer-image" %>
      <p><%= current_customer.shop_name %></p>
      <p>出品数:<%= current_customer.products.count %>&nbsp;&nbsp;&nbsp;&nbsp;取引数:<%= current_customer.orders.count %></p>
    </div>
  
  
    <div class="menu-btn-modal">
      <div class="modal-btn"><%= link_to "マイページ", customer_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "プロフィール", customer_show_profile_path(current_customer.id), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "本人情報", edit_customer_path(current_customer.id), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "#{ current_customer.followings.count }フォロー中", customer_followings_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "#{ current_customer.followers.count }フォロワー", customer_followers_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "オファーした商品", customer_offers_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "オファーされた商品", customer_offered_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "オファー成立商品(準備中)", customer_orders_listing_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "オファー成立商品(取引中)",customer_orders_in_progress_path(current_customer), class:"text-dark" %></div>
  
    </div>
  </div>
  <% else %>
  <div class="bar-menu bar-menu-modal-wrapper">
  
    <div class="menu-btn-modal">
      <div class="modal-btn"><%= link_to "新規登録", new_customer_registration_path, class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "ログイン", new_customer_session_path, class:"text-dark" %></div>
    </div>
  </div>
<% end %>

app/views/layouts/_category_menu_modal.html.erb
<div class="category-menu category-menu-modal-wrapper">

  <div class="search-form">
    <%= form_with url: search_path, method: :get, local: true do |f| %>
      <%= f.text_field :keyword, placeholder: "キーワードを入力" %>
      <%= f.submit 'Search' %>
    <% end %>
  </div>

  <div class="category-menu-btn-modal">
    <div class="category-modal-btn"><%= link_to "野菜", product_index_1_path, class:"text-dark" %></div>
    <div class="category-modal-btn"><%= link_to "果物", product_index_2_path, class:"text-dark" %></div>
    <div class="category-modal-btn"><%= link_to "米・穀物", product_index_3_path, class:"text-dark" %></div>
    <div class="category-modal-btn"><%= link_to "加工食品", product_index_4_path, class:"text-dark" %></div>
    <div class="category-modal-btn"><%= link_to "飲料", product_index_5_path, class:"text-dark" %></div>
    <div class="category-modal-btn"><%= link_to "その他", product_index_6_path, class:"text-dark" %></div>
    <div class="category-modal-btn"><%= link_to "その他(飲食店)", product_index_7_path, class:"text-dark" %></div>
    <div class="category-modal-btn"><%= link_to "その他(その他ユーザー)", product_index_8_path, class:"text-dark" %></div>
  </div>
</div>

app/views/layouts/_menu_modal.html.erb
<% if customer_signed_in? %>
  <div class="mypage menu-modal-wrapper">
    <div class="profile-detail-modal">
      <%= attachment_image_tag current_customer, :customer_image, format: 'jpeg', fallback: 'no_image.jpg' ,class: "menu-modal-customer-image" %>
      <p><%= current_customer.shop_name %></p>
      <p>出品数:<%= current_customer.products.count %>&nbsp;&nbsp;&nbsp;&nbsp;取引数:<%= current_customer.orders.count %></p>
    </div>
    <div class="menu-btn-modal">
      <div class="modal-btn"><%= link_to "プロフィール", customer_show_profile_path(current_customer.id), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "本人情報", edit_customer_path(current_customer.id), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "#{ current_customer.followings.count }フォロー中", customer_followings_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "#{ current_customer.followers.count }フォロワー", customer_followers_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "オファーした商品", customer_offers_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "オファーされた商品", customer_offered_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "オファー成立商品(準備中)", customer_orders_listing_path(current_customer), class:"text-dark" %></div>
      <div class="modal-btn"><%= link_to "オファー成立商品(取引中)",customer_orders_in_progress_path(current_customer), class:"text-dark" %></div>
  
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Barters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/6d90d7dbcd.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% unless admin_signed_in? %>
      <header>
          <div class="btn-right-wrapper">
            <div class="bar-menu">
              <i class="fas fa-bars"></i>
            </div>
            <div class="menu-right">
              <%= link_to product_index_1_path, class:"text-success btn-right category-menu" do %>
                <i class="fas fa-caret-square-down">カテゴリー</i>
              <% end %>
              <% if customer_signed_in? %>
                <%= link_to destroy_customer_session_path, method: :delete, class:"text-success btn-right" do %>
                  <i class="fas fa-sign-out-alt">ログアウト</i>
                <% end %>
                <%= link_to customer_path(current_customer), class:"text-success btn-right mypage" do %>
                  <p><%= attachment_image_tag @customer, :customer_image, format: 'jpeg', fallback: 'no_image.jpg' , size: "50x50", class: "customer-image" %>マイページ</p>
                <% end %>
              <% else %>
                <%= link_to new_customer_registration_path, class:"text-success btn-right" do %>
                  <i class="fas fa-user-plus">新規登録</i>
                <% end %>
                <%= link_to new_customer_session_path, class:"text-success btn-right" do %>
                  <i class="fas fa-sign-in-alt">ログイン</i>
                <% end %>
              <% end %>
            </div>
          </div>


          <%= link_to  root_path do %>
            <%= image_tag "logo_transparent.png", class: "logo_image" %>
          <% end %>




          <% unless customer_signed_in? %>
            <%= link_to homes_guest_sign_in_path, method: :post, class:"btn btn-danger guest_sign_in_btn" do %>
              <i class="fas fa-sign-in-alt">ゲストログイン（閲覧用）</i>
            <% end %>
          <% end %>
      </header>
    <% else %>
      <header>
          <div class="btn-right-wrapper">
            <div class="admin-bar-menu">
              <i class="fas fa-bars"></i>
            </div>
          </div>
          <%= link_to  admins_products_path do %>
            <%= image_tag "logo_transparent.png", class: "logo_image" %>
          <% end %>
          <div class="admin-login">
            <h8>管理者ログイン中</h8>
          </div>
      </header>
    <% end %>
    <%= render "layouts/menu_modal" %>
    <%= render "layouts/bar_menu_modal" %>
    <%= render "layouts/admin_menu_modal" %>
    <%= render "layouts/category_menu_modal" %>
    <%= yield %>
  </body>
</html>

<script>
  $('.mypage').hover(function(){
    $('.menu-modal-wrapper').css("display","block");
  },function(){
      $('.menu-modal-wrapper').css("display", "none");
  });


  $('.bar-menu').hover(function(){
    $('.bar-menu-modal-wrapper').css("display","block");
  },function(){
    $('.bar-menu-modal-wrapper').css("display", "none");
  });

  $('.admin-bar-menu').hover(function(){
    $('.admin-bar-menu-modal-wrapper').css("display","block");
  },function(){
    $('.admin-bar-menu-modal-wrapper').css("display", "none");
  });

  $('.category-menu').hover(function(){
    $('.category-menu-modal-wrapper').css("display","block");
  },function(){
      $('.category-menu-modal-wrapper').css("display", "none");
  });


</script>